# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertSpreader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(blank=True, max_length=256, null=True)),
                ('ident_number', models.CharField(blank=True, max_length=16, null=True)),
                ('date_purchased', models.DateField()),
                ('in_commission', models.BooleanField(default=True)),
                ('capacity', models.FloatField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128)),
                ('model', models.TextField(max_length=256)),
                ('year', models.IntegerField()),
                ('ident_number', models.CharField(blank=True, max_length=16, null=True)),
                ('date_purchased', models.DateField()),
                ('hours', models.FloatField()),
                ('in_commission', models.BooleanField(default=True)),
                ('oil_capacity', models.FloatField(blank=True, null=True)),
                ('hyd_oil_capacity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Aerator',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='Mower',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
                ('cut_height', models.FloatField()),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='Roller',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
                ('roll_width', models.FloatField(blank=True, null=True)),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='Sprayer',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
                ('tank_capacity', models.IntegerField()),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='Tractor',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='TrapRake',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
                ('plow', models.BooleanField()),
                ('plow_attached', models.BooleanField(default=False)),
            ],
            bases=('machines.machine',),
        ),
        migrations.CreateModel(
            name='UtilVehicle',
            fields=[
                ('machine_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Machine')),
                ('bed_size', models.FloatField(blank=True, null=True)),
            ],
            bases=('machines.machine',),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuel_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_fuel_filter_+', to='parts.Filter'),
        ),
        migrations.AddField(
            model_name='machine',
            name='fuel_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_fuel_type_+', to='parts.Fuel'),
        ),
        migrations.AddField(
            model_name='machine',
            name='hyd_oil_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_hyd_oil_filter_+', to='parts.Filter'),
        ),
        migrations.AddField(
            model_name='machine',
            name='hyd_oil_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_hyd_oil_type_+', to='parts.Oil'),
        ),
        migrations.AddField(
            model_name='machine',
            name='oil_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_oil_filter_+', to='parts.Filter'),
        ),
        migrations.AddField(
            model_name='machine',
            name='oil_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_oil_type_+', to='parts.Oil'),
        ),
        migrations.CreateModel(
            name='FairwayMower',
            fields=[
                ('mower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Mower')),
            ],
            bases=('machines.mower',),
        ),
        migrations.CreateModel(
            name='GreensMower',
            fields=[
                ('mower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Mower')),
            ],
            bases=('machines.mower',),
        ),
        migrations.CreateModel(
            name='RoughMower',
            fields=[
                ('mower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Mower')),
            ],
            bases=('machines.mower',),
        ),
        migrations.CreateModel(
            name='TeeMower',
            fields=[
                ('mower_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='machines.Mower')),
            ],
            bases=('machines.mower',),
        ),
    ]
