# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-30 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='serial',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
