# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('machines', '0002_auto_20180430_1639'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.FloatField()),
                ('date', models.DateField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(max_length=128)),
                ('year', models.IntegerField()),
                ('mileage', models.FloatField()),
                ('date_purchased', models.DateField()),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('serial', models.CharField(blank=True, max_length=128, null=True)),
                ('oil_capacity', models.FloatField(blank=True, null=True)),
                ('hyd_oil_capacity', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fuel_filter', models.ManyToManyField(blank=True, related_name='_truck_fuel_filter_+', to='parts.Filter')),
                ('fuel_type', models.ManyToManyField(blank=True, related_name='_truck_fuel_type_+', to='parts.Fuel')),
                ('hyd_oil_filter', models.ManyToManyField(blank=True, related_name='_truck_hyd_oil_filter_+', to='parts.Filter')),
                ('hyd_oil_type', models.ManyToManyField(blank=True, related_name='_truck_hyd_oil_type_+', to='parts.Oil')),
                ('oil_filter', models.ManyToManyField(blank=True, related_name='_truck_oil_filter_+', to='parts.Filter')),
                ('oil_type', models.ManyToManyField(blank=True, related_name='_truck_oil_type_+', to='parts.Oil')),
            ],
        ),
    ]
