# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_hourreading_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hourreading',
            name='date',
        ),
    ]
