# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_auto_20180207_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
