# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-01 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_remove_hourreading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hourreading',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
