# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_auto_20180207_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='ident_number',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
