# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_auto_20180207_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='FertSpreader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=128)),
                ('model', models.CharField(blank=True, max_length=256, null=True)),
                ('ident_number', models.CharField(blank=True, max_length=16, null=True)),
                ('notes', models.TextField()),
            ],
        ),
    ]
