# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0001_initial'),
        ('machines', '0005_hourreading_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='air_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_air_filter_+', to='parts.Filter'),
        ),
    ]
