# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measures', '0004_timeunit'),
        ('machines', '0006_machine_air_filter'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertspreader',
            name='units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='oil_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mower',
            name='height_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.DistanceUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roller',
            name='width_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.DistanceUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprayer',
            name='tank_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='truck',
            name='oil_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='utilvehicle',
            name='bed_units',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertspreader',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
