# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0006_fertspreader'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertspreader',
            name='capacity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='in_commission',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='traprake',
            name='plow_attached',
            field=models.BooleanField(default=False),
        ),
    ]
