# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20180227_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='fuel_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_fuel_filter_+', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='fuel_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_fuel_type_+', to='parts.Fuel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_hyd_oil_filter_+', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_hyd_oil_type_+', to='parts.Oil'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_filter',
            field=models.ManyToManyField(blank=True, related_name='_machine_oil_filter_+', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_type',
            field=models.ManyToManyField(blank=True, related_name='_machine_oil_type_+', to='parts.Oil'),
        ),
    ]
