# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 14:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_auto_20180504_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertspreader',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='mower',
            name='height_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.DistanceUnit'),
        ),
        migrations.AlterField(
            model_name='roller',
            name='width_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.DistanceUnit'),
        ),
        migrations.AlterField(
            model_name='sprayer',
            name='tank_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='utilvehicle',
            name='bed_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
        ),
    ]
