# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-08 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_auto_20180504_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertspreader',
            name='units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cap_unit', to='measures.Unit'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='air_filter',
            field=models.ManyToManyField(blank=True, related_name='mach_air_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='fuel_filter',
            field=models.ManyToManyField(blank=True, related_name='mach_fuel_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='fuel_type',
            field=models.ManyToManyField(blank=True, related_name='machine_fuel', to='parts.Fuel'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_filter',
            field=models.ManyToManyField(blank=True, related_name='mach_hyd_oil_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_type',
            field=models.ManyToManyField(blank=True, related_name='mach_hyd_oil', to='parts.Oil'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mach_hyd_unit', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_filter',
            field=models.ManyToManyField(blank=True, related_name='mach_oil_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_type',
            field=models.ManyToManyField(blank=True, related_name='machine_oil', to='parts.Oil'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mach_oil_units', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='mower',
            name='height_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='height_unit', to='measures.DistanceUnit'),
        ),
        migrations.AlterField(
            model_name='roller',
            name='width_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='width_unit', to='measures.DistanceUnit'),
        ),
        migrations.AlterField(
            model_name='sprayer',
            name='tank_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tank_unit', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_filter',
            field=models.ManyToManyField(blank=True, related_name='truck_fuel_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='fuel_type',
            field=models.ManyToManyField(blank=True, related_name='truck_fuel', to='parts.Fuel'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='hyd_oil_filter',
            field=models.ManyToManyField(blank=True, related_name='truck_hyd_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='hyd_oil_type',
            field=models.ManyToManyField(blank=True, related_name='truck_hyd', to='parts.Oil'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='hyd_oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_hyd_unit', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='oil_filter',
            field=models.ManyToManyField(blank=True, related_name='truck_oil_filter', to='parts.Filter'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='oil_type',
            field=models.ManyToManyField(blank=True, related_name='truck_oil', to='parts.Oil'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='oil_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_oil_unit', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='utilvehicle',
            name='bed_units',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bed_unit', to='measures.Unit'),
        ),
    ]
