# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_auto_20180325_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertspreader',
            name='date_purchased',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
