# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_fertspreader_date_purchased'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertspreader',
            name='in_commission',
            field=models.BooleanField(default=True),
        ),
    ]
