# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbreviation', models.CharField(max_length=12)),
            ],
        ),
        migrations.AddField(
            model_name='rateunit',
            name='denominator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='den', to='measures.Unit'),
        ),
        migrations.AddField(
            model_name='rateunit',
            name='numerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='num', to='measures.Unit'),
        ),
    ]
