# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_tee_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stimp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simple_version', models.BooleanField()),
                ('forward1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forward2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forward3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('forwardAvg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('backward1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('backward2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('backward3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('backwardAvg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('left1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('left2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('left3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('leftAvg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('right1', models.DecimalField(decimal_places=2, max_digits=12)),
                ('right2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('right3', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rightAvg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stdDev', models.DecimalField(decimal_places=5, max_digits=15)),
                ('mu_k', models.DecimalField(decimal_places=5, max_digits=15)),
                ('raw_speed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('adj_speed', models.DecimalField(decimal_places=2, max_digits=12)),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Green')),
            ],
        ),
    ]
