# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aerating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aerate_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FairwayAerating',
            fields=[
                ('aerating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerating.Aerating')),
                ('fairway', models.ManyToManyField(to='courses.Fairway')),
            ],
            bases=('aerating.aerating',),
        ),
        migrations.CreateModel(
            name='GreensAerating',
            fields=[
                ('aerating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerating.Aerating')),
                ('green', models.ManyToManyField(to='courses.Green')),
            ],
            bases=('aerating.aerating',),
        ),
        migrations.CreateModel(
            name='RoughAerating',
            fields=[
                ('aerating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerating.Aerating')),
                ('rough', models.ManyToManyField(to='courses.Rough')),
            ],
            bases=('aerating.aerating',),
        ),
        migrations.CreateModel(
            name='TeeAerating',
            fields=[
                ('aerating_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aerating.Aerating')),
                ('tee', models.ManyToManyField(to='courses.Tee')),
            ],
            bases=('aerating.aerating',),
        ),
        migrations.AddField(
            model_name='aerating',
            name='aerator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Aerator'),
        ),
    ]
