# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-06-06 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aerating', '0003_deeptine'),
    ]

    operations = [
        migrations.AddField(
            model_name='aerating',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
