# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fluid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=256)),
                ('alt_part_no', models.CharField(max_length=256)),
                ('make', models.CharField(max_length=256)),
                ('location', models.TextField()),
                ('in_stock', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('part_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Part')),
            ],
            bases=('parts.part',),
        ),
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('fluid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Fluid')),
            ],
            bases=('parts.fluid',),
        ),
        migrations.CreateModel(
            name='Oil',
            fields=[
                ('fluid_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parts.Fluid')),
            ],
            bases=('parts.fluid',),
        ),
    ]
