# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0002_auto_20180207_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='fluid',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='part',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='part',
            name='obsolete',
            field=models.BooleanField(default=False),
        ),
    ]
