# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 14:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0008_auto_20180504_0933'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measures', '0004_timeunit'),
        ('courses', '0002_tee_notes'),
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scientific_name', models.CharField(max_length=256)),
                ('common_name', models.CharField(blank=True, max_length=256, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemManufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChemUsedInSpray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_used_per_tank', models.FloatField()),
                ('rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('notes', models.TextField()),
                ('susceptible', models.ManyToManyField(to='turfs.TurfgrassSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Spraying',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spray_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tanks_sprayed', models.FloatField()),
                ('water_per_tank', models.FloatField()),
                ('area_covered', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeChem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_name', models.CharField(max_length=128)),
                ('unit_size', models.FloatField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spraying.Chemical')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spraying.ChemManufacturer')),
                ('units', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='FairwaySpraying',
            fields=[
                ('spraying_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spraying.Spraying')),
                ('fairways', models.ManyToManyField(to='courses.Fairway')),
            ],
            bases=('spraying.spraying',),
        ),
        migrations.CreateModel(
            name='GreensSpraying',
            fields=[
                ('spraying_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spraying.Spraying')),
                ('surrounds', models.BooleanField()),
                ('greens', models.ManyToManyField(to='courses.Green')),
            ],
            bases=('spraying.spraying',),
        ),
        migrations.CreateModel(
            name='RoughSpraying',
            fields=[
                ('spraying_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spraying.Spraying')),
                ('roughs', models.ManyToManyField(to='courses.Rough')),
            ],
            bases=('spraying.spraying',),
        ),
        migrations.CreateModel(
            name='TeeSpraying',
            fields=[
                ('spraying_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='spraying.Spraying')),
                ('tees', models.ManyToManyField(to='courses.Tee')),
            ],
            bases=('spraying.spraying',),
        ),
        migrations.AddField(
            model_name='spraying',
            name='area_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.AreaUnit'),
        ),
        migrations.AddField(
            model_name='spraying',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='spraying',
            name='sprayer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Sprayer'),
        ),
        migrations.AddField(
            model_name='spraying',
            name='water_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.VolumeUnit'),
        ),
        migrations.AddField(
            model_name='chemusedinspray',
            name='chemical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spraying.TradeChem'),
        ),
        migrations.AddField(
            model_name='chemusedinspray',
            name='rate_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.RateUnit'),
        ),
        migrations.AddField(
            model_name='chemusedinspray',
            name='spray',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spraying.Spraying'),
        ),
        migrations.AddField(
            model_name='chemusedinspray',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measures.Unit'),
        ),
        migrations.AddField(
            model_name='chemical',
            name='targets',
            field=models.ManyToManyField(to='spraying.Pest'),
        ),
    ]
