# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spraying', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemusedinspray',
            name='rate_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.RateUnit'),
        ),
        migrations.AlterField(
            model_name='chemusedinspray',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='area_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.AreaUnit'),
        ),
        migrations.AlterField(
            model_name='spraying',
            name='water_units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.VolumeUnit'),
        ),
        migrations.AlterField(
            model_name='tradechem',
            name='units',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='measures.Unit'),
        ),
    ]
