# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BunkerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nickname', models.CharField(blank=True, max_length=256, null=True)),
                ('par', models.IntegerField(default=4)),
                ('yardage', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole', to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='TurfFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('mow_direction', models.DecimalField(decimal_places=24, default=0, max_digits=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fairway',
            fields=[
                ('turffeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fairway', to='courses.Hole')),
            ],
            bases=('courses.turffeature',),
        ),
        migrations.CreateModel(
            name='Green',
            fields=[
                ('turffeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='green', to='courses.Hole')),
            ],
            bases=('courses.turffeature',),
        ),
        migrations.CreateModel(
            name='Rough',
            fields=[
                ('turffeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rough', to='courses.Hole')),
            ],
            bases=('courses.turffeature',),
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('turffeature_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tee', to='courses.Hole')),
            ],
            bases=('courses.turffeature',),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AddField(
            model_name='bunker',
            name='bunker_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.BunkerLocation'),
        ),
        migrations.AddField(
            model_name='bunker',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunker', to='courses.Hole'),
        ),
    ]
