# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BunkerLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Fairway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Green',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Hole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('nickname', models.CharField(max_length=256)),
                ('par', models.IntegerField(default=4)),
                ('yardage', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Rough',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType')),
                ('turf_cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar')),
                ('turf_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies')),
            ],
        ),
        migrations.CreateModel(
            name='Tee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole')),
                ('soil_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType')),
                ('turf_cultivar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar')),
                ('turf_species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies')),
            ],
        ),
        migrations.AddField(
            model_name='green',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
        migrations.AddField(
            model_name='green',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AddField(
            model_name='green',
            name='turf_cultivar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AddField(
            model_name='green',
            name='turf_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AddField(
            model_name='fairway',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
        migrations.AddField(
            model_name='fairway',
            name='soil_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AddField(
            model_name='fairway',
            name='turf_cultivar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AddField(
            model_name='fairway',
            name='turf_species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AddField(
            model_name='bunker',
            name='bunker_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.BunkerLocation'),
        ),
        migrations.AddField(
            model_name='bunker',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
    ]
