# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 20:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fairway',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AlterField(
            model_name='fairway',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AlterField(
            model_name='fairway',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AlterField(
            model_name='green',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AlterField(
            model_name='green',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AlterField(
            model_name='green',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AlterField(
            model_name='rough',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AlterField(
            model_name='rough',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AlterField(
            model_name='rough',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AlterField(
            model_name='tee',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AlterField(
            model_name='tee',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AlterField(
            model_name='tee',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
    ]
