# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turfs', '0002_auto_20180206_2046'),
        ('courses', '0002_auto_20180206_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='area',
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='id',
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='turf_cultivar',
        ),
        migrations.RemoveField(
            model_name='fairway',
            name='turf_species',
        ),
        migrations.RemoveField(
            model_name='green',
            name='area',
        ),
        migrations.RemoveField(
            model_name='green',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='green',
            name='id',
        ),
        migrations.RemoveField(
            model_name='green',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='green',
            name='turf_cultivar',
        ),
        migrations.RemoveField(
            model_name='green',
            name='turf_species',
        ),
        migrations.RemoveField(
            model_name='rough',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='rough',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rough',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='rough',
            name='turf_cultivar',
        ),
        migrations.RemoveField(
            model_name='rough',
            name='turf_species',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='area',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='hole',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='soil_type',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='turf_cultivar',
        ),
        migrations.RemoveField(
            model_name='tee',
            name='turf_species',
        ),
        migrations.AlterField(
            model_name='hole',
            name='nickname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='soil_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType'),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='turf_cultivar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar'),
        ),
        migrations.AddField(
            model_name='turffeature',
            name='turf_species',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies'),
        ),
        migrations.AddField(
            model_name='fairway',
            name='turffeature_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='green',
            name='turffeature_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rough',
            name='turffeature_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tee',
            name='turffeature_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.TurfFeature'),
            preserve_default=False,
        ),
    ]
