# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180219_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hole',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hole', to='courses.Course'),
        ),
    ]
