# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 02:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20180227_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turffeature',
            name='hole',
        ),
        migrations.AddField(
            model_name='fairway',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fairway', to='courses.Hole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='green',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='green', to='courses.Hole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rough',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rough', to='courses.Hole'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tee',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tee', to='courses.Hole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bunker',
            name='hole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bunker', to='courses.Hole'),
        ),
    ]
