# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-09 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20180228_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='turffeature',
            name='mow_direction',
            field=models.DecimalField(decimal_places=24, default=0, max_digits=32),
        ),
    ]
