# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turfs', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('build_date', models.DateField()),
                ('details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BuildBunker',
            fields=[
                ('build_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='building.Build')),
                ('bunker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Bunker')),
            ],
            bases=('building.build',),
        ),
        migrations.CreateModel(
            name='BuildFairway',
            fields=[
                ('build_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='building.Build')),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar')),
                ('fairway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Fairway')),
                ('soil_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies')),
            ],
            bases=('building.build',),
        ),
        migrations.CreateModel(
            name='BuildGreen',
            fields=[
                ('build_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='building.Build')),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Green')),
                ('soil_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies')),
            ],
            bases=('building.build',),
        ),
        migrations.CreateModel(
            name='BuildTee',
            fields=[
                ('build_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='building.Build')),
                ('cultivar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.Cultivar')),
                ('soil_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.SoilType')),
                ('species', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turfs.TurfgrassSpecies')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tee')),
            ],
            bases=('building.build',),
        ),
    ]
