# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('parts', '0001_initial'),
        ('machines', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ooc', models.DateTimeField(auto_now_add=True)),
                ('date_fixed', models.DateTimeField(blank=True, null=True)),
                ('hours_on_machine', models.FloatField()),
                ('description', models.TextField()),
                ('parts_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepairPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
            ],
        ),
        migrations.CreateModel(
            name='OilChange',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Maintenance')),
                ('oil_qty', models.DecimalField(decimal_places=2, max_digits=12)),
                ('oil_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('oil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Oil')),
            ],
            bases=('maintenance.maintenance',),
        ),
        migrations.CreateModel(
            name='Repair',
            fields=[
                ('maintenance_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='maintenance.Maintenance')),
            ],
            bases=('maintenance.maintenance',),
        ),
        migrations.AddField(
            model_name='repairpart',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Maintenance'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='acked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Machine'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='parts_used',
            field=models.ManyToManyField(blank=True, to='maintenance.RepairPart'),
        ),
    ]
