# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 13:06
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('machines', '0009_auto_20180508_0326'),
        ('maintenance', '0002_oilchange_oil_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedknifeToReel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime(2018, 5, 12, 13, 6, 7, 203988, tzinfo=utc))),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='machines.Mower')),
            ],
        ),
    ]
