# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-10 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parts', '0006_auto_20180328_0826'),
        ('maintenance', '0002_maintenance_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepairPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parts.Part')),
            ],
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='parts_used',
            field=models.ManyToManyField(blank=True, to='maintenance.RepairPart'),
        ),
        migrations.AddField(
            model_name='repairpart',
            name='repair',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Maintenance'),
        ),
    ]
