# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-12 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_bedknifetoreel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bedknifetoreel',
            name='date',
            field=models.DateField(),
        ),
    ]
