# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_repair_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repair',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='repair',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='maintenance',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
