# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-29 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_auto_20180329_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12),
        ),
    ]
