# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rolling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FairwayRolling',
            fields=[
                ('rolling_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rolling.Rolling')),
                ('fairway', models.ManyToManyField(to='courses.Fairway')),
            ],
            bases=('rolling.rolling',),
        ),
        migrations.CreateModel(
            name='GreensRolling',
            fields=[
                ('rolling_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rolling.Rolling')),
                ('green', models.ManyToManyField(to='courses.Green')),
            ],
            bases=('rolling.rolling',),
        ),
        migrations.CreateModel(
            name='TeeRolling',
            fields=[
                ('rolling_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rolling.Rolling')),
                ('tee', models.ManyToManyField(to='courses.Tee')),
            ],
            bases=('rolling.rolling',),
        ),
        migrations.AddField(
            model_name='rolling',
            name='roller',
            field=models.ManyToManyField(to='machines.Roller'),
        ),
    ]
