# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('hole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Hole')),
            ],
        ),
        migrations.CreateModel(
            name='IrrigationDig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('drain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.Drain')),
            ],
        ),
        migrations.CreateModel(
            name='QuickCoupler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('fairway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Fairway')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Green')),
                ('rough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Rough')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tee')),
            ],
        ),
        migrations.CreateModel(
            name='SatelliteBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_number', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='SprinklerHead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprinkler_number', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('distance', models.IntegerField()),
                ('fairway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Fairway')),
                ('green', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Green')),
                ('rough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Rough')),
                ('satellite_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.SatelliteBox')),
                ('tee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tee')),
            ],
        ),
        migrations.AddField(
            model_name='irrigationdig',
            name='quick_coupler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.QuickCoupler'),
        ),
        migrations.AddField(
            model_name='irrigationdig',
            name='sprinkler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irrigation.SprinklerHead'),
        ),
    ]
