# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_auto_20180206_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quickcoupler',
            name='fairway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Fairway'),
        ),
        migrations.AlterField(
            model_name='quickcoupler',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Green'),
        ),
        migrations.AlterField(
            model_name='quickcoupler',
            name='rough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Rough'),
        ),
        migrations.AlterField(
            model_name='quickcoupler',
            name='tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Tee'),
        ),
        migrations.AlterField(
            model_name='sprinklerhead',
            name='fairway',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Fairway'),
        ),
        migrations.AlterField(
            model_name='sprinklerhead',
            name='green',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Green'),
        ),
        migrations.AlterField(
            model_name='sprinklerhead',
            name='rough',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Rough'),
        ),
        migrations.AlterField(
            model_name='sprinklerhead',
            name='tee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Tee'),
        ),
    ]
