# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0002_shutoffvalve_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='shutoffvalve',
            name='handle',
            field=models.TextField(default='handle'),
        ),
    ]
