# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-06 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_auto_20180206_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinklerhead',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
