# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-26 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0003_shutoffvalve_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='drain',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
