# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 12:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0004_auto_20180206_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigationdig',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
