# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_auto_20180219_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shutoffvalve',
            old_name='status',
            new_name='open',
        ),
    ]
