# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-08 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0006_electronicvalve'),
    ]

    operations = [
        migrations.AddField(
            model_name='drain',
            name='handle_type',
            field=models.CharField(default='handle', max_length=256),
            preserve_default=False,
        ),
    ]
