# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('irrigation', '0007_auto_20180227_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drain',
            old_name='status',
            new_name='open',
        ),
    ]
