# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-28 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20180219_1710'),
        ('irrigation', '0008_auto_20180227_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprinklerhead',
            name='hole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
        ),
    ]
