# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_turffeature_mow_direction'),
        ('irrigation', '0011_auto_20180325_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='irrigationdig',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='irrigationdig',
            name='hole',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courses.Hole'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='irrigationdig',
            name='drain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigation.Drain'),
        ),
        migrations.AlterField(
            model_name='irrigationdig',
            name='quick_coupler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irrigation.QuickCoupler'),
        ),
    ]
