# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-23 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('machines', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=128)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('n_value', models.PositiveIntegerField()),
                ('p_value', models.PositiveIntegerField()),
                ('k_value', models.PositiveIntegerField()),
                ('bag_size', models.PositiveIntegerField()),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fert_date', models.DateTimeField(auto_now=True)),
                ('bags_used', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FairwayFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('fairway', models.ManyToManyField(to='courses.Fairway')),
            ],
            options={
                'verbose_name_plural': 'Fairway fertilizations',
            },
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='GreensFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('green', models.ManyToManyField(to='courses.Green')),
            ],
            options={
                'verbose_name_plural': 'Greens fertilizations',
            },
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='RoughFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('rough', models.ManyToManyField(to='courses.Rough')),
            ],
            options={
                'verbose_name_plural': 'Rough fertilizations',
            },
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='TeeFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('tee', models.ManyToManyField(to='courses.Tee')),
            ],
            options={
                'verbose_name_plural': 'Tee fertilizations',
            },
            bases=('fertilizing.fertilizing',),
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizing.Fertilizer'),
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='spreader',
            field=models.ManyToManyField(to='machines.FertSpreader'),
        ),
    ]
