# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-07 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_auto_20180206_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=128)),
                ('n_value', models.PositiveIntegerField()),
                ('p_value', models.PositiveIntegerField()),
                ('k_value', models.PositiveIntegerField()),
                ('bag_size', models.PositiveIntegerField()),
                ('price_per_bag', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fert_date', models.DateTimeField(auto_now=True)),
                ('rate', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FairwayFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('fairway', models.ManyToManyField(to='courses.Fairway')),
            ],
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='GreensFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('green', models.ManyToManyField(to='courses.Green')),
            ],
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='RoughFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('rough', models.ManyToManyField(to='courses.Rough')),
            ],
            bases=('fertilizing.fertilizing',),
        ),
        migrations.CreateModel(
            name='TeeFert',
            fields=[
                ('fertilizing_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fertilizing.Fertilizing')),
                ('tee', models.ManyToManyField(to='courses.Tee')),
            ],
            bases=('fertilizing.fertilizing',),
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='fertilizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizing.Fertilizer'),
        ),
    ]
