# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-19 03:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fairwayfert',
            options={'verbose_name_plural': 'Fairway fertilizations'},
        ),
        migrations.AlterModelOptions(
            name='greensfert',
            options={'verbose_name_plural': 'Greens fertilizations'},
        ),
        migrations.AlterModelOptions(
            name='roughfert',
            options={'verbose_name_plural': 'Rough fertilizations'},
        ),
        migrations.AlterModelOptions(
            name='teefert',
            options={'verbose_name_plural': 'Tee fertilizations'},
        ),
    ]
