# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-20 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizing', '0002_auto_20180219_0332'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizing',
            name='bags_used',
            field=models.FloatField(),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='manufacturer',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='fertilizer',
            name='name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
