# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizing', '0003_auto_20180220_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizing',
            name='bags_used',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fertilizing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
