# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizing', '0004_auto_20180227_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fertilizing',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
