# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_auto_20180228_1324'),
        ('fertilizing', '0007_fertilizer_spreader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fertilizer',
            name='spreader',
        ),
        migrations.AddField(
            model_name='fertilizer',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fertilizing',
            name='spreader',
            field=models.ManyToManyField(to='machines.FertSpreader'),
        ),
    ]
