# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-11-02 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='additional_workers',
            field=models.ManyToManyField(blank=True, null=True, related_name='task_workers', to='labor.Employee'),
        ),
    ]
